# Generated by Django 4.0.1 on 2022-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='token',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='address',
            field=models.CharField(default='no address', max_length=200),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='email_id',
            field=models.EmailField(default='xxx@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(default='rather not to say', max_length=20),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='ph_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
