# Generated by Django 2.2.10 on 2022-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220129_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='path',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
